### ISSUE TITLE
Unable to log into web account for EDGE

### ISSUE THREAD

**Issue by rlahowetz2** [LANL-Bioinformatics/EDGE#65]
Hi, I am currently able to log into EDGE or reset my password. 

When I click the login button and enter my email/password it states "Login Failed" and asks if I entered the right credentials. When I try to reset my password I get the error "Exception: ResetPasswd failed. Invalid email 'rachel.lahowetz@bcm.edu' or your are not an active user." However, when tried to make a new account with the same email address I got an error reading "This email address is already taken". I tried several times and copied/pasted my email to make sure that there isn't a typo causing the issue. 

I've been able to use EDGE web version in the past without issue, until a few weeks ago when I initially couldn't log in, then was unable to access the website at all (I believe a labmate also had a similar issue at that time).  I am currently able to use it as a guest. 

Spec info: Windows 11 Home, Firefox 129.0.2 (64-bit), EDGE v2.4.1 dev (on website).

Any help would be greatly appreciated!

Thank you,
Rachel

**Comment by mflynn-lanl** [comment]
Hi Rachel,
I activated your account. Let me know if you're still having issues authenticating
Cheers,
Mark
________________________________
From: rlahowetz2 ***@***.***>
Sent: Tuesday, September 3, 2024 10:57 AM
To: LANL-Bioinformatics/EDGE ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [LANL-Bioinformatics/EDGE] Unable to log into web account for EDGE (Issue #65)


Hi, I am currently able to log into EDGE or reset my password.

When I click the login button and enter my email/password it states "Login Failed" and asks if I entered the right credentials. When I try to reset my password I get the error "Exception: ResetPasswd failed. Invalid email ***@***.******@***.***>' or your are not an active user." However, when tried to make a new account with the same email address I got an error reading "This email address is already taken". I tried several times and copied/pasted my email to make sure that there isn't a typo causing the issue.

I've been able to use EDGE web version in the past without issue, until a few weeks ago when I initially couldn't log in, then was unable to access the website at all (I believe a labmate also had a similar issue at that time). I am currently able to use it as a guest.

Spec info: Windows 11 Home, Firefox 129.0.2 (64-bit), EDGE v2.4.1 dev (on website).

Any help would be greatly appreciated!

Thank you,
Rachel

**Comment by rlahowetz2** [comment]
Hi Mark, 

I'm still having issues - I get the same error when I try to log in. Now, if I click to reset my password there is just an empty box instead of any text. 

I also tried on Microsoft Edge and have the same issue there. 

![image](https://github.com/user-attachments/assets/bd403d5b-23c8-4070-8d83-480eb80feb78)

**Comment by mflynn-lanl** [comment]
Hi Rachel,
There was a problem with the password reset function. I've fixed it and tested it on Chrome, Firefox and Safari. Unfortunately I cannot test on Microsoft EDGE, so please let me know if you have any problems using that browser.
Cheers,
Mark
________________________________
From: rlahowetz2 ***@***.***>
Sent: Wednesday, September 4, 2024 10:41 AM
To: LANL-Bioinformatics/EDGE ***@***.***>
Cc: Flynn, Mark C ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [LANL-Bioinformatics/EDGE] Unable to log into web account for EDGE (Issue #65)


Hi Mark,

I'm still having issues - I get the same error when I try to log in. Now, if I click to reset my password there is just an empty box instead of any text.

I also tried on Microsoft Edge and have the same issue there.

image.png (view on web)<https://urldefense.com/v3/__https://github.com/user-attachments/assets/bd403d5b-23c8-4070-8d83-480eb80feb78__;!!Bt8fGhp8LhKGRg!GXDQXSueWL5L5FmK8n0vWfIWgymmMVv2JN6-Y4Ipts4VQ8k9Ey8VtizDJqU1vZg4NNaSfeVRGjZ5cTzjzOljvSIJ$>

**Comment by rlahowetz2** [comment]
I was able to reset my password and logged in using Firefox, thank you!
